Remove the need to do an array cast
hhvm/fbexpect pull request #24
Opened 2019-11-19 23:20 UTC by lexidor

This function seems like it wants to avoid `dict<_, _>` `vec<_>` and `keyset<_>`.
This is where it acme from and hwere it is still used until this day: https://github.com/hhvm/fbexpect/commit/76be22ec078e8977befa7420f0a9cb52c8335e84

2019-11-22 01:15 UTC, jjergus requested changes
This changes the behavior for darrays, but if the places you linked to are the only callsites and we don't care about varray vs darray there, maybe just remove the function and inline the code there?

I'd rather not keep a function around if it has somewhat confusing unexpected behavior (throwing away darray keys).

2019-11-22 17:56 UTC, lexidor commented
I moved this function into the class and removed a callsite in toNotContainSubString(). As a plus, now you don't need `as Traversable<_>` anymore, since the types are checked for the typechecker too.

2019-11-25 23:59 UTC, jjergus commented
Sorry I didn't realize this earlier, but couldn't we just remove the function?

As far as I can tell, `assertContains` and `assertNotContains` work just fine with any Traversable, we shouldn't need to convert anything... Or am I missing something?

2019-11-26 15:29 UTC, lexidor commented
I have gone back in time and it appears that this was done when HackTest relied on PHPUnit for some assertions. PHPUnit did not know about Hack arrays, so they needed to be cast to arrays. In the modern post-PHP day, this code is a relic of the past. I will remove this.

2019-12-02 16:45 UTC, merged