Add assert and remove phpunit
hhvm/fbexpect pull request #4
Opened 2018-07-18 23:55 UTC by wlin57

I apologize in advance -- this diff is huge but all of these pieces need to be in place simultaneously in order to remove PHPUnit as a dependency entirely.

- PHPUnit is gone! Using HackTest to run tests
- Most of the logic for asserts is from PHPUnit, so nothing too special
- Added hh_autoload
- Added custom exception classes
- Removed one test that used toEqualWithDelta with arrays (restrict to num)

TODO (in another PR):
- Use hacktest in travis (this travis build will fail)
- Update README

Once this lands I can:
- Remove PHPUnit as a dependency from HackTest
- Check for my custom exceptions (rather than the PHPUnit versions) in external version of HackTest (www has its own version of expect)
- Remove PHPUnit from HSL 
- Submit diff to refactor HSL to use HackTest (basically ready, waiting for this)
- After above, update all three repos' (HackTest, HSL, FBExpect) composer.lock so that PHPUnit stuff doesn't show up anymore

2018-07-19 00:02 UTC, kmeht commented on src/Assert.php
> +    if (empty($actual) == true) {
remove == true

2018-07-25 21:12 UTC, fredemmott commented
:/ hopefully the bot is drunk.

Triggered a retest now that the bot is public, but composer.json needs updating to no longer directly reference the repository

2018-07-27 21:51 UTC, fredemmott requested changes
I'm pretty sure the nightly build is failing due to a parse error here. This probably shouldn't be happening as it's passing on the current release, but it needs isolating, and either we need it fixed in hackc or worked around here

2018-07-27 21:55 UTC, fredemmott commented
hh_client gets me:

```
src/Assert.php:355:54,53: Method call following immediate constructor call requires parentheses around constructor call. (Parsing[1002])
```

This is an intentional breakage in hack, and needs fixing here

2018-07-27 22:25 UTC, fredemmott commented
There's more - you probably want to `brew unlink hhvm; brew install hhvm-nightly` then you can reproduce the problem locally in hh_client

2018-07-28 00:07 UTC, wlin57 commented
Can't seem to reproduce errors after installing hhvm-nightly.
```
wlin21-mbp:fbexpect wlin21$ hh_client
For more detailed logs, try `tail -f $(hh_client --monitor-logname) $(hh_client --logname)`
Server launched with the following command:
	'/usr/local/Cellar/hhvm-nightly/2018.07.27/bin/hh_server' '-d' '/Users/wlin21/Desktop/fbexpect' '--waiting-client' '5'
Spawned typechecker (child pid=95500)
Logs will go to /private/tmp/hh_server/monitor_logs/zSUserszSwlin21zSDesktopzSfbexpect-2018-07-27-17-06-41.monitor_log
No errors!
```

2018-07-28 00:20 UTC, fredemmott commented
How about vendor/bin/hh-autoload

2018-07-31 19:50 UTC, wlin57 commented
```
wlin21-mbp:fbexpect wlin21$ vendor/bin/hh-autoload

Fatal error: Uncaught exception 'HH\InvariantException' with message 'FactParse typesshould be an array<shape('name' => string)>' in /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/TypeAssert.php:127
Stack trace:
#0 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/TypeAssert.php(127): HH\invariant_violation()
#1 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/FactParseScanner.php(46): Facebook\AutoloadMap\__Private\TypeAssert\is_array_of_shapes_with_name_field()
#2 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/FactParseScanner.php(124): Facebook\AutoloadMap\FactParseScanner::untypedToShape()
#3 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/HHImporter.php(89): Facebook\AutoloadMap\FactParseScanner->getAutoloadMap()
#4 (): Closure$Facebook\AutoloadMap\HHImporter::getAutoloadMap()
#5 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/HHImporter.php(89): HH\Vector->map()
#6 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/RootImporter.php(54): Facebook\AutoloadMap\HHImporter->getAutoloadMap()
#7 (): Closure$Facebook\AutoloadMap\RootImporter::getAutoloadMap()
#8 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/RootImporter.php(54): HH\Vector->map()
#9 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/Writer.php(64): Facebook\AutoloadMap\RootImporter->getAutoloadMap()
#10 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/bin/hh-autoload(96): Facebook\AutoloadMap\Writer->setBuilder()
#11 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/bin/hh-autoload(47): Facebook\AutoloadMap\GenerateScript::initAutoloader()
#12 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/bin/hh-autoload(113): Facebook\AutoloadMap\GenerateScript::main()
#13 {main}

Next exception 'Exception' with message 'Failed to parse '/Users/wlin21/Desktop/fbexpect/src/Assert.php"' in /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/FactParseScanner.php:68
Stack trace:
#0 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/FactParseScanner.php(124): Facebook\AutoloadMap\FactParseScanner::untypedToShape()
#1 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/HHImporter.php(89): Facebook\AutoloadMap\FactParseScanner->getAutoloadMap()
#2 (): Closure$Facebook\AutoloadMap\HHImporter::getAutoloadMap()
#3 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/HHImporter.php(89): HH\Vector->map()
#4 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/RootImporter.php(54): Facebook\AutoloadMap\HHImporter->getAutoloadMap()
#5 (): Closure$Facebook\AutoloadMap\RootImporter::getAutoloadMap()
#6 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/RootImporter.php(54): HH\Vector->map()
#7 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/Writer.php(64): Facebook\AutoloadMap\RootImporter->getAutoloadMap()
#8 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/bin/hh-autoload(96): Facebook\AutoloadMap\Writer->setBuilder()
#9 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/bin/hh-autoload(47): Facebook\AutoloadMap\GenerateScript::initAutoloader()
#10 /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/bin/hh-autoload(113): Facebook\AutoloadMap\GenerateScript::main()
#11 {main}
```

2018-07-31 20:00 UTC, fredemmott commented
```
Next exception 'Exception' with message 'Failed to parse '/Users/wlin21/Desktop/fbexpect/src/Assert.php"' in /Users/wlin21/Desktop/fbexpect/vendor/hhvm/hhvm-autoload/src/builders/FactParseScanner.php:68
```

So, that's showing issues in src/Assert.php

2018-07-31 21:38 UTC, fredemmott commented
If you run the master of HHAST against this or update the dependency to hhast 3.27.2, it should detect and autofix this problem

2018-07-31 22:36 UTC, merged